### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by McFlyssss** [beelsebob/CoreParse#42]
We are developing an app that uses CoreParse for parsing specific strings. I realised that the library leaks memory at some point. The most critical leak is in <code>CPShiftReduceParser</code> when instantiating a <code>CPRHSItemResult</code>

In order to fix this leak i just modified this line:
<code>result = [(id\<CPParseResult\>)[c alloc] initWithSyntaxTree:tree];</code>

and added the <code>autorelease</code> call
<code>result = [[(id\<CPParseResult\>)[c alloc] initWithSyntaxTree:tree] autorelease];</code>

This fixed several leaks for me.

**Comment by beelsebob** [comment]
Hi McFlyssss,  Looking at the git history, this leak appears to have been fixed a couple of years ago.  Have you pulled the most recent version of CoreParse?  Do you have your remote set up to point at some other repository that has not pulled from github recently?
